services:
  postgres:
    image: postgres:15
    container_name: tesla_complaints_db
    environment:
      POSTGRES_USER: mateo
      POSTGRES_PASSWORD: R0m@n2o0two
      POSTGRES_DB: tesla_complaints
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: